# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/bcap_server.rb'

Hoe.new('bcap_server', BcapServer::VERSION) do |p|
  # p.rubyforge_name = 'bcap_serverx' # if different than lowercase project name
  p.developer('Brandon Caplan', 'maelmann@gmail.com')
end

# vim: syntax=Ruby
