# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/bcap_chat.rb'

Hoe.new('bcap_chat', BcapChat::VERSION) do |p|
  # p.rubyforge_name = 'bcap_chatx' # if different than lowercase project name
  # p.developer('FIX', 'FIX@example.com')
end

# vim: syntax=Ruby
